---
language: python
services: docker
os: linux
dist: bionic
env:
  - MOLECULE_DISTRO: centos8
  - MOLECULE_DISTRO: centos7
  - MOLECULE_DISTRO: debian10
  - MOLECULE_DISTRO: ubuntu20.04
  - MOLECULE_DISTRO: ubuntu18.04
  - MOLECULE_DISTRO: ubuntu16.04
  - MOLECULE_DISTRO: fedora32
  - MOLECULE_DISTRO: fedora31
  - MOLECULE_DISTRO: fedora30
  - MOLECULE_DISTRO: fedora29

install:
  - pip install molecule yamllint ansible-lint docker
script:
  - molecule test
